server {
  listen 80;
  server_name _;

  large_client_header_buffers 4 32k;
  client_header_buffer_size 16k;

  root /usr/share/nginx/html;
  index index.html;

  location = /favicon.ico {
    try_files /favicon.svg =204;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
